FROM ubuntu:14.04

MAINTAINER Krutika Gaonkar (gaonkark@email.chop.edu)

# maintainer
MAINTAINER Krutika Gaonkar

RUN apt-get update && apt-get install -y \
	tar \
	tcl \
	bedtools \
	autoconf \
	automake \
	python2.7 \
	python-pip \
	make \
	g++ \
	gcc \
	build-essential \ 
	zlib1g-dev \
	libgsl0-dev \
	perl \
	curl \
	git \
	wget \
	unzip \
	tabix \
	bzip2 \
	libncurses5-dev \
	build-essential \
	openssl

ARG PACKAGE_VERSION=2.27.1

WORKDIR /opt
RUN git clone https://github.com/arq5x/bedtools2.git
RUN cd bedtools2
RUN make 

WORKDIR /opt
RUN wget https://lbgi.fr/AnnotSV/Sources/AnnotSV_2.1.tar.gz
RUN tar -xvf AnnotSV_2.1.tar.gz
